// The Drizzle schema — the single source of truth for every table Postgres has, read by both
// drizzle-kit (migrations, via drizzle.config.ts) and the app at runtime (via db/client.ts).
// Two halves:
//   1. Better Auth's core tables (user/session/account/verification) — generated by
//      `bunx @better-auth/cli generate` against src/lib/auth.ts, then hand-merged here so they
//      migrate alongside our own tables in one pass. Regenerate + re-diff by hand if the Better
//      Auth config ever changes shape (new plugin, new field) — the CLI doesn't own this file.
//   2. Ambit's own tables, per SPEC.md §5 (item/topic/user_topic/saved_item/invite).
//
// No `ambit_`-style table-name prefix: that pattern (from the create-t3-app starter) exists so
// one Postgres instance can host several unrelated apps without table-name collisions. This
// compose Postgres is dedicated to Ambit alone, so the prefix would be pure ceremony — and SPEC's
// own SQL (§5) already writes the tables unprefixed (`item`, `topic`, `"user"`, ...), so dropping
// it also keeps this file a direct, literal match for the spec.
import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { nanoid } from "nanoid";

// ---------------------------------------------------------------------------------------------
// Better Auth core tables (generated, then owned here — see the file header)
// ---------------------------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  // Phase 5.10's two profile columns. Both nullable so the Better Auth sign-up insert — and the
  // invite-gate `user.create.before` databaseHook that runs with it (lib/auth.ts) — never has to
  // know these columns exist; a user who never opens /profile/edit simply has null in both.
  //
  // `handle` is stored BARE and LOWERCASE ("bentraverse", never "@BenTraverse"): the client strips
  // a typed `@` and `user.updateProfile` lowercases, so the unique constraint below can't be
  // sidestepped by case alone. Rendered as `@{handle}`. Display-only — there are no public
  // profiles, so nothing resolves a handle back to a user.
  //
  // Postgres treats NULLs as distinct for uniqueness, so unlimited users can have no handle at
  // all while the constraint still holds for everyone who sets one.
  handle: text("handle").unique(),
  bio: text("bio"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    // The scrypt hash of the user's password (email+password sign-in is just another "account",
    // Better Auth's generalized-provider model — `providerId: "credential"` for this row).
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    // What's being verified (an email address, a password-reset request, ...) and the token/code
    // value itself — used for both email verification (unused here, SPEC §3.1) and password reset.
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ---------------------------------------------------------------------------------------------
// Ambit's own tables — SPEC.md §5
// ---------------------------------------------------------------------------------------------

// `topic.seed_queries` shape firms up in Phase 2.3 (server/config/topics.ts): per-source arrays
// of search queries that seed a topic's ingestion. Loosely typed here on purpose — the JSONB
// column itself is settled now, but nailing the exact per-source query shape is that step's job.
type SeedQueries = Record<string, string[]>;

export const topic = pgTable("topic", {
  // Not a nanoid: topic ids are slugs Ambit assigns by hand (`ancient-history`, `the-ocean`, ...),
  // one per row in the checked-in topic-adjacency graph (server/config/topic-graph.json). They're
  // config, not user data — seed-topics.ts (Phase 2.3) supplies the id explicitly on insert.
  id: text("id").primaryKey(),
  label: text("label").notNull(),
  seedQueries: jsonb("seed_queries").$type<SeedQueries>().notNull(),
});

export const item = pgTable(
  "item",
  {
    // nanoid, generated here (not by Postgres) so the app can know an item's id before insert —
    // `$defaultFn` runs client-side, once per row, the first time Drizzle builds the insert.
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    source: text("source").notNull(), // 'wikipedia' | 'met' | 'aic' | 'cma' | 'wellcome' | ... (open set — grows through Phase 3/6 as adapters come online)
    sourceId: text("source_id").notNull(), // this item's id within that source
    // A genuinely closed set (SPEC §3), so `$type` buys real narrowing here — unlike `source`
    // above, which SPEC deliberately leaves open-ended.
    type: text("type").$type<"image" | "article">().notNull(),
    title: text("title").notNull(),
    summary: text("summary"), // lede / synopsis
    body: text("body"), // full article text; articles only
    imageUrl: text("image_url"), // images / illustrated articles
    sourceUrl: text("source_url").notNull(), // canonical link back to the source
    attribution: text("attribution"), // required by some sources' terms
    license: text("license"),
    // Native source tags (Wikipedia categories, Met department/medium/culture, ...) — a secondary
    // signal only; the curation score + topic graph are the feed's primary drivers (SPEC §9).
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    // The item's DISPLAY topic — nullable since Cut 1 of the vocabulary-growth design (09-2026,
    // docs/DESIGN_topic-vocabulary-growth.md §5). For a search-shaped source it is still the topic
    // whose seed query surfaced the item; for a walk source it is the first honest topic the
    // curator named; for a walk item no current topic fits it is NULL ("un-homed"). Full
    // membership — an item can honestly belong to several topics — lives in `item_topic` below.
    //
    // The feed still draws on THIS column until Cut 2 moves it onto the join (db/feed.ts
    // `getTopicPools`, db/items.ts `drawFromTopic`). Both filter with `inArray`/`eq`, and SQL NULL
    // matches neither, so an un-homed item is invisible to every feed draw with no guard at all.
    // It stays reachable by direct link (`/i/[itemId]`) and by the gallery's wildcard slots.
    topicId: text("topic_id").references(() => topic.id),
    curationScore: real("curation_score").notNull(), // 1–10 from the ingest-time LLM curator (SPEC §6.2)
    // The curator's own look/appeal keywords ("botanical plate", "hand-lettered") — overlap with a
    // user's taste keywords boosts an item's draw weight within its topic (SPEC §9).
    aestheticTags: text("aesthetic_tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    fetchedAt: timestamp("fetched_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    // Idempotent ingestion hangs off this: upsert-by-(source, source_id) means re-running the
    // ingestion job never double-inserts the same museum object or Wikipedia article.
    unique("item_source_sourceId_unique").on(table.source, table.sourceId),
    index("idx_item_type").on(table.type),
    index("idx_item_source").on(table.source),
    // The feed's actual draw path (SPEC §6.3 `drawFromTopic`): "give me unseen items in this
    // topic, weighted by score" — a composite index so that query doesn't scan the whole table.
    index("idx_item_topic_score").on(table.topicId, table.curationScore),
    // GIN (Generalized Inverted Index) is the index type Postgres needs for containment queries
    // (`tags @> ARRAY['x']`) on an array column — a plain btree index can't do that efficiently.
    index("idx_item_tags_gin").using("gin", table.tags),
  ],
);

/** How an `item_topic` row came to exist — the fact Cut 2's promotion audits on. Deliberately no
 *  `confidence` column: an LLM's self-reported confidence is uncalibrated, and Phase 0's lesson was
 *  to stop trusting similarity numbers. Weighting, if ever wanted, derives from this plus
 *  `curation_score`, both of which are real. */
export type ItemTopicOrigin =
  /** A search source's seed query surfaced the item under this topic (the museum path). */
  | "seed"
  /** The curator's classify mode named it (walk sources). */
  | "curator"
  /** A Cut 2 promotion backfilled it from tag overlap. Unused until then. */
  | "tag";

/**
 * Topic membership, many-to-many (Cut 1, design §5). One row per (item, topic) an item honestly
 * belongs to. **Membership is additive**: every writer uses `ON CONFLICT DO NOTHING`, and no
 * automated process ever deletes a row — adding a topic can only widen an item's reach, removing
 * one silently takes it out of feeds. Removal is a deliberate, human-triggered act that Cut 1
 * does not build.
 *
 * `onDelete: "cascade"` on `item_id` because `--prune` and `bun run retire` delete items, and a
 * membership without its item is meaningless. **No cascade on `topic_id`**: deleting a topic
 * while items still reference it should fail loudly.
 */
export const itemTopic = pgTable(
  "item_topic",
  {
    itemId: text("item_id")
      .notNull()
      .references(() => item.id, { onDelete: "cascade" }),
    topicId: text("topic_id")
      .notNull()
      .references(() => topic.id),
    origin: text("origin").$type<ItemTopicOrigin>().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.itemId, table.topicId] }),
    // Cut 2's promotion and "everything in topic X" both read by topic; the PK serves by item.
    index("idx_item_topic_topic").on(table.topicId),
  ],
);

export const userTopic = pgTable(
  "user_topic",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    topicId: text("topic_id")
      .notNull()
      .references(() => topic.id),
    // Adjusted as the feed learns (SPEC §9): saving an item nudges its topic's weight up, visibly.
    weight: real("weight").notNull().default(1.0),
  },
  (table) => [primaryKey({ columns: [table.userId, table.topicId] })],
);

// A user's named buckets for saved items (SPEC §5.4c, Phase 5.5). Three defaults — Articles, Art,
// Photos — are seeded *lazily*, on the first read in db/collections.ts, rather than at sign-up:
// nothing before Phase 5.5 needed them, so seeding on read means existing users get theirs without
// a backfill migration.
export const collection = pgTable(
  "collection",
  {
    // nanoid generated app-side, same reason as `item` and `invite`: the app knows the id before
    // the insert lands.
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    // Load-bearing for the lazy seeding above, not just hygiene: two concurrent first-reads (a
    // double-mounted React 19 dev render is enough) both try to insert the three defaults, and
    // this constraint is what turns the loser's `onConflictDoNothing` into a no-op instead of a
    // duplicate "Articles" row.
    unique("uq_collection_user_name").on(table.userId, table.name),
    index("idx_collection_user").on(table.userId),
  ],
);

export const savedItem = pgTable(
  "saved_item",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    itemId: text("item_id")
      .notNull()
      .references(() => item.id),
    // Which collection this save lives in — **nullable**, meaning "saved but uncollected": such a
    // row is counted by the UI's "Everything kept" total but appears under no named collection.
    //
    // One collection per item, by construction: this table's primary key is (user_id, item_id), so
    // there is exactly one row per saved item and therefore exactly one collection. That's the
    // design's own model (the prototypes key collections as `{ [itemId]: collectionName }`, render
    // a single accent dot, and label exactly one row "Already saved here") — picking a different
    // collection *moves* the item via an UPDATE rather than adding a second membership.
    //
    // `set null` rather than `cascade`: deleting a collection must never silently delete the
    // user's saves. Collection deletion isn't built yet (creation lands in 5.10); the constraint
    // is written correctly now so that phase doesn't have to migrate it.
    collectionId: text("collection_id").references(() => collection.id, {
      onDelete: "set null",
    }),
    savedAt: timestamp("saved_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.itemId] }),
    index("idx_saved_item_user").on(table.userId),
  ],
);

// The feed's "almost never repeating" promise (SPEC §9.4): every item a user has ever been
// served, retained forever (no TTL/pruning — Phase 4.1 decision). Deliberately *not* keyed by a
// synthetic id/timestamp-only PK: (userId, itemId) is the natural key (a user either has or
// hasn't seen a given item), and its composite btree already answers the feed's only query shape
// ("what has this user seen"), so there's no separate user_id index to add (SPEC §5.6 doesn't
// list one for this table for the same reason).
export const seenItem = pgTable(
  "seen_item",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    itemId: text("item_id")
      .notNull()
      .references(() => item.id),
    // When the reader was actually *handed* this item, set explicitly from the app clock rather
    // than defaultNow(). As of 5.7 the writer is the client's receipt ack (`feed.markSeen`), not
    // the server render — a render whose output gets discarded must not spend corpus. So this
    // timestamp now lands strictly *after* the cursor `anchor` of the page it belongs to, which is
    // exactly what keeps a refetch of that same cursor from excluding its own page. See
    // services/feed.ts's cursor design note for the full argument.
    servedAt: timestamp("served_at", { withTimezone: true }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.itemId] })],
  // No extra user_id index: the composite PK's btree already serves user-scoped lookups.
);

export const invite = pgTable("invite", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => nanoid()),
  email: text("email").notNull().unique(),
  status: text("status")
    .$type<"pending" | "accepted">()
    .default("pending")
    .notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});
