// The Drizzle schema — the single source of truth for every table Postgres has, read by both
// drizzle-kit (migrations, via drizzle.config.ts) and the app at runtime (via db/client.ts).
// Two halves:
//   1. Better Auth's core tables (user/session/account/verification) — generated by
//      `bunx @better-auth/cli generate` against src/lib/auth.ts, then hand-merged here so they
//      migrate alongside our own tables in one pass. Regenerate + re-diff by hand if the Better
//      Auth config ever changes shape (new plugin, new field) — the CLI doesn't own this file.
//   2. Ambit's own tables, per SPEC.md §5 (item/topic/user_topic/saved_item/invite).
//
// No `ambit_`-style table-name prefix: that pattern (from the create-t3-app starter) exists so
// one Postgres instance can host several unrelated apps without table-name collisions. This
// compose Postgres is dedicated to Ambit alone, so the prefix would be pure ceremony — and SPEC's
// own SQL (§5) already writes the tables unprefixed (`item`, `topic`, `"user"`, ...), so dropping
// it also keeps this file a direct, literal match for the spec.
import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { nanoid } from "nanoid";

// ---------------------------------------------------------------------------------------------
// Better Auth core tables (generated, then owned here — see the file header)
// ---------------------------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    // The scrypt hash of the user's password (email+password sign-in is just another "account",
    // Better Auth's generalized-provider model — `providerId: "credential"` for this row).
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    // What's being verified (an email address, a password-reset request, ...) and the token/code
    // value itself — used for both email verification (unused here, SPEC §3.1) and password reset.
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// ---------------------------------------------------------------------------------------------
// Ambit's own tables — SPEC.md §5
// ---------------------------------------------------------------------------------------------

// `topic.seed_queries` shape firms up in Phase 2.3 (server/config/topics.ts): per-source arrays
// of search queries that seed a topic's ingestion. Loosely typed here on purpose — the JSONB
// column itself is settled now, but nailing the exact per-source query shape is that step's job.
type SeedQueries = Record<string, string[]>;

export const topic = pgTable("topic", {
  // Not a nanoid: topic ids are slugs Ambit assigns by hand (`ancient-history`, `the-ocean`, ...),
  // one per row in the checked-in topic-adjacency graph (server/config/topic-graph.json). They're
  // config, not user data — seed-topics.ts (Phase 2.3) supplies the id explicitly on insert.
  id: text("id").primaryKey(),
  label: text("label").notNull(),
  seedQueries: jsonb("seed_queries").$type<SeedQueries>().notNull(),
});

export const item = pgTable(
  "item",
  {
    // nanoid, generated here (not by Postgres) so the app can know an item's id before insert —
    // `$defaultFn` runs client-side, once per row, the first time Drizzle builds the insert.
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    source: text("source").notNull(), // 'wikipedia' | 'met' | 'aic' | 'cma' | 'wellcome' | ... (open set — grows through Phase 3/6 as adapters come online)
    sourceId: text("source_id").notNull(), // this item's id within that source
    // A genuinely closed set (SPEC §3), so `$type` buys real narrowing here — unlike `source`
    // above, which SPEC deliberately leaves open-ended.
    type: text("type").$type<"image" | "article">().notNull(),
    title: text("title").notNull(),
    summary: text("summary"), // lede / synopsis
    body: text("body"), // full article text; articles only
    imageUrl: text("image_url"), // images / illustrated articles
    sourceUrl: text("source_url").notNull(), // canonical link back to the source
    attribution: text("attribution"), // required by some sources' terms
    license: text("license"),
    // Native source tags (Wikipedia categories, Met department/medium/culture, ...) — a secondary
    // signal only; the curation score + topic graph are the feed's primary drivers (SPEC §9).
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    topicId: text("topic_id")
      .notNull()
      .references(() => topic.id), // which topic's seed query surfaced this item — the feed's unit of drift
    curationScore: real("curation_score").notNull(), // 1–10 from the ingest-time LLM curator (SPEC §6.2)
    // The curator's own look/appeal keywords ("botanical plate", "hand-lettered") — overlap with a
    // user's taste keywords boosts an item's draw weight within its topic (SPEC §9).
    aestheticTags: text("aesthetic_tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    fetchedAt: timestamp("fetched_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    // Idempotent ingestion hangs off this: upsert-by-(source, source_id) means re-running the
    // ingestion job never double-inserts the same museum object or Wikipedia article.
    unique("item_source_sourceId_unique").on(table.source, table.sourceId),
    index("idx_item_type").on(table.type),
    index("idx_item_source").on(table.source),
    // The feed's actual draw path (SPEC §6.3 `drawFromTopic`): "give me unseen items in this
    // topic, weighted by score" — a composite index so that query doesn't scan the whole table.
    index("idx_item_topic_score").on(table.topicId, table.curationScore),
    // GIN (Generalized Inverted Index) is the index type Postgres needs for containment queries
    // (`tags @> ARRAY['x']`) on an array column — a plain btree index can't do that efficiently.
    index("idx_item_tags_gin").using("gin", table.tags),
  ],
);

export const userTopic = pgTable(
  "user_topic",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    topicId: text("topic_id")
      .notNull()
      .references(() => topic.id),
    // Adjusted as the feed learns (SPEC §9): saving an item nudges its topic's weight up, visibly.
    weight: real("weight").notNull().default(1.0),
  },
  (table) => [primaryKey({ columns: [table.userId, table.topicId] })],
);

export const savedItem = pgTable(
  "saved_item",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    itemId: text("item_id")
      .notNull()
      .references(() => item.id),
    savedAt: timestamp("saved_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.itemId] }),
    index("idx_saved_item_user").on(table.userId),
  ],
);

export const invite = pgTable("invite", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => nanoid()),
  email: text("email").notNull().unique(),
  status: text("status")
    .$type<"pending" | "accepted">()
    .default("pending")
    .notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});
