// The writing curator's calibration (docs/DESIGN_writing.md D1, docs/PLAN_writing.md Phase 1):
// the pure half of `bun run writing:calibrate`. Ben rates ~40 pieces by hand in
// `docs/writing-calibration.md`, the script compares his marks with the models', and the prompt
// is iterated until they agree. **That agreement is the gate before any re-score.**
//
// The file is both the questionnaire and the record: the models' answers are written into it, so
// `--read` needs no network and a later reader can see exactly what Ben was agreeing with.

import {
  isWritingKind,
  WRITING_KINDS,
  type WritingKind,
} from "~/server/config/writing";

export type CalibrationAnswer = {
  model: string;
  score: number;
  kind: WritingKind | null;
  tags: string[];
  topics: string[];
};

export type CalibrationEntry = {
  n: number;
  itemId: string;
  /** `source:sourceId` — what the curator's cache is keyed on. */
  key: string;
  title: string;
  source: string;
  minutes: number | null;
  /** The image rubric's score, from before the writing curator. */
  oldScore: number;
  url: string;
  excerpt: string;
  answers: CalibrationAnswer[];
  ben: {
    score: number | null;
    kind: WritingKind | null;
    note: string;
  };
};

// ── sampling ────────────────────────────────────────────────────────────────

/** The old score's band: the image rubric's floor (≤4), its middle, and its top. */
export function scoreBand(score: number): "low" | "mid" | "high" {
  return score <= 4 ? "low" : score <= 6 ? "mid" : "high";
}

/**
 * Up to `n` rows, spread across every source and old-score band present: sources take turns, and
 * within a source its bands take turns (each band shuffled by `rng`), until `n` are drawn or
 * nothing is left. Source first, so a source spanning three bands gets no more turns than one
 * sitting in a single band. Turn-taking rather than proportional, on purpose: Loupe has ~130
 * articles to Wikipedia's thousands, and a sample that is 95% Wikipedia calibrates nothing
 * about the others.
 */
export function stratifiedSample<
  T extends { source: string; curationScore: number },
>(rows: readonly T[], n: number, rng: () => number): T[] {
  const shuffled = (xs: T[]) => {
    const q = [...xs];
    for (let i = q.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      [q[i], q[j]] = [q[j]!, q[i]!];
    }
    return q;
  };
  // source → band → rows. Sources take turns; within a source, its bands take turns.
  const bySource = new Map<string, Map<string, T[]>>();
  for (const r of rows) {
    const bands = bySource.get(r.source) ?? new Map<string, T[]>();
    const band = scoreBand(r.curationScore);
    bands.set(band, [...(bands.get(band) ?? []), r]);
    bySource.set(r.source, bands);
  }
  const sources = [...bySource.keys()].sort().map((src) => {
    const bands = bySource.get(src)!;
    return {
      queues: [...bands.keys()].sort().map((b) => shuffled(bands.get(b)!)),
      turn: 0,
    };
  });
  const next = (s: (typeof sources)[number]): T | undefined => {
    // At most one full lap of this source's bands, starting where its last turn left off.
    for (let lap = s.queues.length; lap > 0; lap--) {
      const q = s.queues[s.turn++ % s.queues.length]!;
      const r = q.shift();
      if (r) return r;
    }
    return undefined;
  };
  const out: T[] = [];
  while (out.length < n) {
    let drew = false;
    for (const s of sources) {
      if (out.length >= n) break;
      const r = next(s);
      if (r) {
        out.push(r);
        drew = true;
      }
    }
    if (!drew) break;
  }
  return out;
}

// ── the file ────────────────────────────────────────────────────────────────

const HEADER = `# Writing curator calibration

Generated by \`bun run writing:calibrate --sample\` (docs/PLAN_writing.md Phase 1). For each piece,
fill in the three \`ben-\` lines, then run \`bun run writing:calibrate --read\`.

- **ben-score** — 1-10, your own score for this piece in the feed.
- **ben-kind** — essay · curiosity · criticism · archive (blank if none fits).
- **note** — anything; the five worst disagreements are what the prompt gets tuned against.

The models' answers are in each table. Don't edit those.
`;

const cell = (s: string) => s.replace(/\|/g, "/").replace(/\n/g, " ");

export function renderCalibration(
  entries: readonly CalibrationEntry[],
): string {
  const blocks = entries.map((e) =>
    [
      `## ${e.n}. ${cell(e.title)}`,
      "",
      `- item: ${e.key} · ${e.itemId}`,
      `- source: ${e.source} · minutes: ${e.minutes ?? "—"} · old score: ${e.oldScore}`,
      `- link: ${e.url} · /i/${e.itemId}`,
      "",
      `> ${cell(e.excerpt)}`,
      "",
      "| model | score | kind | tags | topics |",
      "| --- | --- | --- | --- | --- |",
      ...e.answers.map(
        (a) =>
          `| ${a.model} | ${a.score} | ${a.kind ?? "—"} | ${cell(a.tags.join(", "))} | ${a.topics.join(", ")} |`,
      ),
      "",
      `- ben-score: ${e.ben.score ?? ""}`,
      `- ben-kind: ${e.ben.kind ?? ""}`,
      `- note: ${e.ben.note}`,
    ].join("\n"),
  );
  return `${HEADER}\n${blocks.join("\n\n")}\n`;
}

const list = (s: string) =>
  s
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);

function field(block: string, name: string): string {
  return (
    new RegExp(`^- ${name}:[ \\t]*(.*)$`, "m").exec(block)?.[1]?.trim() ?? ""
  );
}

const cells = (line: string) =>
  line
    .slice(1, -1)
    .split("|")
    .map((c) => c.trim());

/** Parse the file back — the models' tables and Ben's marks, read leniently (`8`, `Criticism`).
 *  A blank mark is null. The table is read by its header row, so a file written before 09-30-26
 *  — which had a `timeliness` column and a `ben-news` line — still parses; both are ignored. */
export function parseCalibration(md: string): CalibrationEntry[] {
  return md
    .split(/^## /m)
    .slice(1)
    .map((block) => {
      const [, n = "0", title = ""] = /^(\d+)\. (.*)$/m.exec(block) ?? [];
      const [key = "", itemId = ""] = field(block, "item").split(" · ");
      const meta = /source: (\S+) · minutes: (\S+) · old score: (\S+)/.exec(
        block,
      );
      const [url = ""] = field(block, "link").split(" · ");
      const lines = block.split("\n");
      const header = cells(lines.find((l) => l.startsWith("| model")) ?? "||");
      const answers = lines
        .filter(
          (l) =>
            l.startsWith("| ") &&
            !l.startsWith("| model") &&
            !l.startsWith("| ---"),
        )
        .map((l) => {
          const row = cells(l);
          const col = (name: string) => row[header.indexOf(name)] ?? "";
          const kind = col("kind");
          return {
            model: col("model"),
            score: Number(col("score")),
            kind: isWritingKind(kind) ? kind : null,
            tags: list(col("tags")),
            topics: list(col("topics")),
          };
        });
      const score = Number(field(block, "ben-score"));
      const kind = field(block, "ben-kind").toLowerCase();
      return {
        n: Number(n),
        itemId,
        key,
        title,
        source: meta?.[1] ?? "",
        minutes: meta?.[2] && meta[2] !== "—" ? Number(meta[2]) : null,
        oldScore: Number(meta?.[3] ?? 0),
        url,
        excerpt: /^> (.*)$/m.exec(block)?.[1] ?? "",
        answers,
        ben: {
          score:
            field(block, "ben-score") && Number.isFinite(score) ? score : null,
          kind: isWritingKind(kind) ? kind : null,
          note: field(block, "note"),
        },
      };
    });
}

// ── the report ──────────────────────────────────────────────────────────────

function ranks(xs: readonly number[]): number[] {
  const order = xs.map((x, i) => [x, i] as const).sort((a, b) => a[0] - b[0]);
  const r = new Array<number>(xs.length);
  for (let i = 0; i < order.length;) {
    let j = i;
    while (j + 1 < order.length && order[j + 1]![0] === order[i]![0]) j++;
    for (let k = i; k <= j; k++) r[order[k]![1]] = (i + j) / 2 + 1;
    i = j + 1;
  }
  return r;
}

/** Spearman's rank correlation, ties by average rank. NaN when either side is constant. */
export function spearman(a: readonly number[], b: readonly number[]): number {
  const ra = ranks(a);
  const rb = ranks(b);
  const mean = (xs: number[]) => xs.reduce((s, x) => s + x, 0) / xs.length;
  const ma = mean(ra);
  const mb = mean(rb);
  let cov = 0;
  let va = 0;
  let vb = 0;
  for (let i = 0; i < ra.length; i++) {
    cov += (ra[i]! - ma) * (rb[i]! - mb);
    va += (ra[i]! - ma) ** 2;
    vb += (rb[i]! - mb) ** 2;
  }
  return cov / Math.sqrt(va * vb);
}

type KindCell = WritingKind | "none";

export type ModelReport = {
  model: string;
  /** Entries Ben gave a score. */
  marked: number;
  mae: number;
  spearman: number;
  /** confusion[benKind][modelKind] — over entries Ben gave a kind. */
  confusion: Record<KindCell, Record<KindCell, number>>;
  worst: {
    n: number;
    title: string;
    ben: number;
    model: number;
    note: string;
  }[];
};

/** One report per model found in the file, over the entries Ben has scored. */
export function calibrationReport(
  entries: readonly CalibrationEntry[],
): ModelReport[] {
  const models = [
    ...new Set(entries.flatMap((e) => e.answers.map((a) => a.model))),
  ];
  const kinds: KindCell[] = [...WRITING_KINDS, "none"];
  return models.map((model) => {
    const pairs = entries
      .filter((e) => e.ben.score !== null)
      .flatMap((e) => {
        const a = e.answers.find((x) => x.model === model);
        return a ? [{ e, a }] : [];
      });
    const confusion = Object.fromEntries(
      kinds.map((k) => [k, Object.fromEntries(kinds.map((m) => [m, 0]))]),
    ) as ModelReport["confusion"];
    for (const { e, a } of pairs)
      if (e.ben.kind) confusion[e.ben.kind][a.kind ?? "none"]++;
    const diffs = pairs.map(({ e, a }) => ({
      n: e.n,
      title: e.title,
      ben: e.ben.score!,
      model: a.score,
      note: e.ben.note,
    }));
    return {
      model,
      marked: pairs.length,
      mae:
        diffs.reduce((s, d) => s + Math.abs(d.ben - d.model), 0) / diffs.length,
      spearman: spearman(
        diffs.map((d) => d.ben),
        diffs.map((d) => d.model),
      ),
      confusion,
      worst: [...diffs]
        .sort((x, y) => Math.abs(y.ben - y.model) - Math.abs(x.ben - x.model))
        .slice(0, 5),
    };
  });
}
