// "Where would you go next?" — the destinations question (docs/DESIGN_first-exhibition.md §4).
//
// **Not place topics.** A reader who picks Kyoto is not asking for the `japan` topic; they are
// telling us they're drawn to quiet, old, wet-stone-and-moss places. So a destination carries
// three things, none of them a place:
//   - `topics`: what the place is *made of* (gardens, wood, sacred architecture…), scored like any
//     other answer. Ids that aren't listed yet (proposed topics) are simply dropped by targetsOf.
//   - `axes`: four bipolar scales, each −1…1 — wild (+) / built (−), old (+) / new (−),
//     still (+) / lively (−), far (+) / near (−). The reveal averages the chosen destinations into
//     the "travel compass".
//   - `temperament`: a nudge on the five entertainment dimensions (config/temperament.ts).
//
// Thirty-eight, so the question can rotate later; BALANCED_TWELVE is the fixed set v1 asks
// (three in each quarter of wild/built × old/new). Ben edits this file freely — copy and numbers.

export type TemperamentWeights = Partial<
  Record<"communal" | "aesthetic" | "dark" | "thrilling" | "cerebral", number>
>;

export interface Destination {
  id: string;
  /** What the card says, large. */
  name: string;
  /** Country or region, small caps above the name. */
  where: string;
  /** One line under the name. */
  line: string;
  axes: { wild: number; old: number; still: number; far: number };
  topics: readonly string[];
  temperament: TemperamentWeights;
}

export const DESTINATIONS: readonly Destination[] = [
  {
    id: "kyoto",
    name: "Kyoto in the rain",
    where: "Japan",
    line: "Moss gardens, wet stone, a temple bell.",
    axes: { wild: 0.2, old: 0.8, still: 0.9, far: 0.5 },
    topics: ["gardens", "sacred-architecture", "wood", "ukiyo-e", "melancholy"],
    temperament: { aesthetic: 1 },
  },
  {
    id: "iceland",
    name: "The Icelandic highlands",
    where: "Iceland",
    line: "Black sand, steam, light that never quite sets.",
    axes: { wild: 0.9, old: 0.1, still: 0.6, far: 0.7 },
    topics: ["geology", "landscapes", "volcanoes", "weather", "minimal"],
    temperament: { aesthetic: 0.6, dark: 0.3 },
  },
  {
    id: "marrakech",
    name: "Marrakech medina",
    where: "Morocco",
    line: "Tiled courtyards and a thousand colours.",
    axes: { wild: -0.7, old: 0.6, still: -0.8, far: 0.6 },
    topics: ["islamic-art", "pattern", "markets", "textiles", "color"],
    temperament: { communal: 0.6, aesthetic: 0.5 },
  },
  {
    id: "venice",
    name: "Venice in January",
    where: "Italy",
    line: "Fog on the lagoon, empty palazzi.",
    axes: { wild: -0.6, old: 0.9, still: 0.7, far: 0.2 },
    topics: ["architecture", "water", "melancholy", "renaissance", "painting"],
    temperament: { aesthetic: 0.8, dark: 0.3 },
  },
  {
    id: "tokyo",
    name: "Tokyo after midnight",
    where: "Japan",
    line: "Neon, vending machines, the last trains.",
    axes: { wild: -1, old: -0.7, still: -0.6, far: 0.5 },
    topics: ["neon", "night", "urban-landscape", "cinematic", "technology"],
    temperament: { thrilling: 0.8 },
  },
  {
    id: "berlin",
    name: "Berlin",
    where: "Germany",
    line: "Concrete, clubs and a century of history in one street.",
    axes: { wild: -0.9, old: 0.2, still: -0.7, far: 0.1 },
    topics: ["brutalist", "street-art", "music", "social-history", "bauhaus"],
    temperament: { cerebral: 0.6, dark: 0.4 },
  },
  {
    id: "paris",
    name: "Paris",
    where: "France",
    line: "Museums, cafés, bookshops by the river.",
    axes: { wild: -0.8, old: 0.6, still: -0.2, far: 0 },
    topics: [
      "painting",
      "cafes-and-restaurants",
      "literature",
      "fashion",
      "impressionism",
    ],
    temperament: { aesthetic: 0.7, communal: 0.5 },
  },
  {
    id: "newyork",
    name: "New York",
    where: "United States",
    line: "Art deco towers and every kind of street.",
    axes: { wild: -1, old: 0.1, still: -1, far: -0.3 },
    topics: [
      "architecture",
      "art-deco",
      "street-photography",
      "theatre",
      "food",
    ],
    temperament: { communal: 0.6, thrilling: 0.5 },
  },
  {
    id: "mexicocity",
    name: "Mexico City",
    where: "Mexico",
    line: "Murals, markets, Aztec stone under the streets.",
    axes: { wild: -0.7, old: 0.5, still: -0.7, far: 0.4 },
    topics: ["murals", "folk-art", "pre-columbian", "food", "color"],
    temperament: { communal: 0.8 },
  },
  {
    id: "luxor",
    name: "Luxor and the Valley of the Kings",
    where: "Egypt",
    line: "Painted tombs and the desert at dawn.",
    axes: { wild: 0.3, old: 1, still: 0.5, far: 0.7 },
    topics: ["ancient-egypt", "desert", "ancient-history", "mythology"],
    temperament: { cerebral: 0.6, aesthetic: 0.5 },
  },
  {
    id: "patagonia",
    name: "Patagonia",
    where: "Argentina & Chile",
    line: "Wind, glaciers, granite towers, no one for miles.",
    axes: { wild: 1, old: 0, still: 0.8, far: 0.9 },
    topics: ["mountains", "glaciers", "landscapes", "weather"],
    temperament: { thrilling: 1 },
  },
  {
    id: "svalbard",
    name: "Svalbard in the polar night",
    where: "Norway",
    line: "Aurora, polar bears, a seed vault in the ice.",
    axes: { wild: 0.9, old: -0.1, still: 0.9, far: 1 },
    topics: ["polar", "night", "snow", "light", "science"],
    temperament: { dark: 0.5, cerebral: 0.5 },
  },
  {
    id: "route66",
    name: "Route 66",
    where: "United States",
    line: "Diners, motels, neon in the middle of nowhere.",
    axes: { wild: 0, old: 0.3, still: -0.1, far: -0.3 },
    topics: ["roadside-americana", "neon", "cars", "travel", "nostalgic"],
    temperament: { communal: 0.6, thrilling: 0.4 },
  },
  {
    id: "lisbon",
    name: "Lisbon",
    where: "Portugal",
    line: "Tiled façades, trams, the Atlantic, saudade.",
    axes: { wild: -0.4, old: 0.6, still: 0.1, far: 0.2 },
    topics: ["pattern", "ceramics", "the-ocean", "melancholy", "music"],
    temperament: { aesthetic: 0.6, communal: 0.4 },
  },
  {
    id: "istanbul",
    name: "Istanbul",
    where: "Türkiye",
    line: "Domes and bazaars on two continents.",
    axes: { wild: -0.6, old: 0.8, still: -0.5, far: 0.4 },
    topics: ["islamic-art", "sacred-architecture", "markets", "textiles"],
    temperament: { aesthetic: 0.6, communal: 0.5 },
  },
  {
    id: "rome",
    name: "Rome",
    where: "Italy",
    line: "Ruins in the traffic, Baroque everything.",
    axes: { wild: -0.6, old: 1, still: -0.3, far: 0.1 },
    topics: ["classical-antiquity", "sculpture", "baroque", "ruins", "food"],
    temperament: { aesthetic: 0.7, cerebral: 0.4 },
  },
  {
    id: "galapagos",
    name: "The Galápagos",
    where: "Ecuador",
    line: "Where Darwin watched the finches.",
    axes: { wild: 1, old: 0, still: 0.3, far: 0.9 },
    topics: ["animals", "birds", "natural-history", "marine-life", "science"],
    temperament: { cerebral: 1 },
  },
  {
    id: "cloudforest",
    name: "A cloud forest",
    where: "Costa Rica",
    line: "Hummingbirds, orchids, mist in the canopy.",
    axes: { wild: 1, old: 0, still: 0.4, far: 0.7 },
    topics: ["birds", "plants", "insects", "mushrooms", "nature"],
    temperament: { aesthetic: 0.6, communal: 0.4 },
  },
  {
    id: "detroit",
    name: "Detroit",
    where: "United States",
    line: "Car plants, empty ballrooms, Motown, murals.",
    axes: { wild: -0.6, old: 0.2, still: 0.1, far: 0.2 },
    topics: ["urban-decay", "cars", "music", "murals", "industrial"],
    temperament: { dark: 0.5, cerebral: 0.4 },
  },
  {
    id: "transylvania",
    name: "Transylvania",
    where: "Romania",
    line: "Fortified churches, beech forests, old stories.",
    axes: { wild: 0.5, old: 0.8, still: 0.6, far: 0.6 },
    topics: ["folklore", "castles", "gothic", "horror"],
    temperament: { dark: 0.7, thrilling: 0.4 },
  },
  {
    id: "edinburgh",
    name: "Edinburgh in winter",
    where: "Scotland",
    line: "Closes, crypts, libraries, an old anatomy theatre.",
    axes: { wild: -0.3, old: 0.8, still: 0.3, far: 0.1 },
    topics: ["gothic", "books", "anatomy", "social-history", "literature"],
    temperament: { dark: 0.5, cerebral: 0.6 },
  },
  {
    id: "mara",
    name: "The Maasai Mara",
    where: "Kenya",
    line: "The great migration across the plains.",
    axes: { wild: 1, old: 0.2, still: -0.2, far: 0.8 },
    topics: ["animals", "landscapes", "nature-photography"],
    temperament: { thrilling: 0.7, communal: 0.3 },
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    where: "Denmark",
    line: "Bicycles, design shops, candlelit cafés.",
    axes: { wild: -0.6, old: -0.2, still: 0.3, far: 0 },
    topics: ["industrial-design", "furniture", "cozy", "bicycles"],
    temperament: { communal: 0.6, aesthetic: 0.5 },
  },
  {
    id: "cotswolds",
    name: "The Cotswolds",
    where: "England",
    line: "Stone villages, gardens, a pub fire.",
    axes: { wild: 0.3, old: 0.6, still: 0.9, far: -0.5 },
    topics: ["gardens", "cozy", "pastoral", "houses"],
    temperament: { communal: 1 },
  },
  {
    id: "tuscany",
    name: "Tuscany at harvest",
    where: "Italy",
    line: "Vineyards, cypress roads, long lunches.",
    axes: { wild: 0.3, old: 0.6, still: 0.5, far: 0 },
    topics: ["food", "drinks", "harvest", "renaissance", "landscapes"],
    temperament: { communal: 0.7, aesthetic: 0.5 },
  },
  {
    id: "dubai",
    name: "Dubai",
    where: "United Arab Emirates",
    line: "Glass towers rising out of the desert.",
    axes: { wild: -0.8, old: -1, still: -0.6, far: 0.4 },
    topics: ["future-cities", "desert", "towers", "glamour"],
    temperament: { thrilling: 0.8 },
  },
  {
    id: "himalaya",
    name: "A Himalayan monastery",
    where: "Bhutan",
    line: "Prayer flags, thin air, silence.",
    axes: { wild: 0.7, old: 0.7, still: 1, far: 0.9 },
    topics: ["ritual", "mountains", "sacred-architecture", "textiles"],
    temperament: { aesthetic: 0.6, cerebral: 0.4 },
  },
  {
    id: "rio",
    name: "Rio at Carnival",
    where: "Brazil",
    line: "Feathers, drums, a city dancing for a week.",
    axes: { wild: -0.4, old: -0.1, still: -1, far: 0.5 },
    topics: ["festivals", "dance", "music", "costume", "color"],
    temperament: { communal: 1, thrilling: 0.4 },
  },
  {
    id: "neworleans",
    name: "New Orleans",
    where: "United States",
    line: "Brass bands, cemeteries above ground, gumbo.",
    axes: { wild: -0.4, old: 0.5, still: -0.6, far: 0.1 },
    topics: ["music", "food", "gothic", "festivals"],
    temperament: { communal: 0.7, dark: 0.4 },
  },
  {
    id: "capecanaveral",
    name: "Cape Canaveral",
    where: "United States",
    line: "Launch pads and rockets on the horizon.",
    axes: { wild: -0.2, old: -0.6, still: -0.2, far: 0.1 },
    topics: ["space-exploration", "spaceship", "machines", "technology"],
    temperament: { cerebral: 0.6, thrilling: 0.6 },
  },
  {
    id: "machupicchu",
    name: "Machu Picchu",
    where: "Peru",
    line: "Stone terraces in the clouds.",
    axes: { wild: 0.6, old: 1, still: 0.5, far: 0.8 },
    topics: ["pre-columbian", "mountains", "ancient-history", "ruins"],
    temperament: { aesthetic: 0.5, thrilling: 0.5 },
  },
  {
    id: "angkor",
    name: "Angkor",
    where: "Cambodia",
    line: "Temples swallowed by fig roots.",
    axes: { wild: 0.4, old: 1, still: 0.4, far: 0.8 },
    topics: ["sacred-architecture", "ruins", "ancient-history", "trees"],
    temperament: { aesthetic: 0.6, thrilling: 0.4 },
  },
  {
    id: "barcelona",
    name: "Barcelona",
    where: "Spain",
    line: "Gaudí’s melting buildings, tapas, the beach.",
    axes: { wild: -0.6, old: 0.2, still: -0.6, far: 0.1 },
    topics: ["architecture", "art-nouveau", "mosaics", "surreal", "food"],
    temperament: { aesthetic: 0.6, communal: 0.5 },
  },
  {
    id: "steppe",
    name: "The Mongolian steppe",
    where: "Mongolia",
    line: "Horses, felt tents, sky to every edge.",
    axes: { wild: 1, old: 0.4, still: 0.7, far: 1 },
    topics: ["horses", "landscapes", "textiles", "folk-art"],
    temperament: { thrilling: 0.7, aesthetic: 0.3 },
  },
  {
    id: "alps",
    name: "The Alps by train",
    where: "Switzerland",
    line: "Glacier Express, watchmakers, cold clean air.",
    axes: { wild: 0.6, old: 0.2, still: 0.6, far: 0.1 },
    topics: ["trains", "mountains", "machines", "clocks"],
    temperament: { cerebral: 0.6, aesthetic: 0.3 },
  },
  {
    id: "pripyat",
    name: "Pripyat",
    where: "Ukraine",
    line: "An abandoned city going back to forest.",
    axes: { wild: 0.3, old: -0.2, still: 0.9, far: 0.9 },
    topics: ["urban-decay", "eerie", "soviet", "nature"],
    temperament: { dark: 1 },
  },
  {
    id: "vegas",
    name: "Las Vegas",
    where: "United States",
    line: "Neon, casinos, kitsch at full volume.",
    axes: { wild: -0.9, old: -0.4, still: -1, far: 0 },
    topics: ["neon", "kitsch", "glamour", "roadside-americana"],
    temperament: { thrilling: 0.7, communal: 0.5 },
  },
  {
    id: "seoul",
    name: "Seoul",
    where: "South Korea",
    line: "Palaces, street food, the future arriving early.",
    axes: { wild: -0.8, old: -0.2, still: -0.7, far: 0.5 },
    topics: ["technology", "food", "fashion", "architecture"],
    temperament: { communal: 0.6, thrilling: 0.5 },
  },
];

/** The twelve v1 asks: three per quarter of wild/built × old/new, so no answer is forced. */
export const BALANCED_TWELVE: readonly string[] = [
  "kyoto",
  "iceland",
  "marrakech",
  "venice",
  "tokyo",
  "berlin",
  "luxor",
  "patagonia",
  "istanbul",
  "galapagos",
  "transylvania",
  "copenhagen",
];

/** How many destinations a reader may choose. */
export const DESTINATION_MAX = 3;
